### ISSUE TITLE
Custom LoRaWAN packet format to send archive position data.

### ISSUE THREAD

**Issue by MedadRufus** [bertrik/ttnhabbridge#2]
On long range LoRaWAN flights, such as ICSPACE22 which travelled to Japan from the UK, TTN LoRaWAN coverage is very very poor along the way. With reference to the flight path picture below, the balloon was heard last in Europe, before disappearing for 5 days, and then reappearing in Japan where there is some coverage. Therefore, we have no idea where the balloon was in the 5 days it disappeared.

I am thinking of making a very compact packet structure that combines the current Longitude, Latitude, Altitude, Temperature, Pressure, Sats along with position data from 4 earlier points in time so that we know where the balloon was.

All this has to be done in 26 bytes, to comply with air time restrictions.

This will require me to do bit level optimisation of the packet structure, and possibly use some compression schemes.

In the ttnhabbridge, I would have to make a decoder that will decode this packet. I am planning to make a pull request with this structure if thats alright. This will be in addition to the cayenne format and sodaq one format.

![image](https://user-images.githubusercontent.com/26815217/97361260-2da74f80-1897-11eb-844d-7f16f43f547f.png)

**Comment by MedadRufus** [comment]
Any comments on how to get going with the decoder?

**Comment by bertrik** [comment]
My favourite way of doing this in Java would be to use a ByteBuffer. You can specify the endian-ness, then you can get bytes, 16-bit words, 32-bit words out, etc. I would write a unit test where you put in a byte array with known properties and see that it decodes corretly.I have no idea how we can submit the historical data to habhub though.

**Comment by MedadRufus** [comment]
Thank you for the clues. I have figured out where the parsing happens. I am using the sodaqone parser as reference. I am doing the tests as well.
